title: Adriaan P Hilbers
url: https://ahilbers.github.io
baseurl: "."  # Uncomment for Github build, comment when building locally

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design: Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About Me"
   link: "index"
 - name: "Research"
   link: "research"
 - name: "Projects"
   link: "projects"
 - name: "Contact"
   link: "contact"
