title: Adriaan P Hilbers
url: " "
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design: Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "Research"
   link: "research"
 - name: "Blog"
   link: "blog"
 - name: "Contact"
   link: "contact"
